import {calculateEnergy} from './calculators/energy.mjs';
import {calculateThermo} from './calculators/thermo.mjs';
import {calculateDewPoint} from './calculators/dew-point.mjs';
import {calculateTransmittance} from './calculators/transmittance.mjs';
import {calculateCooling} from './calculators/cooling.mjs';
import {calculatePower} from './calculators/power.mjs';
import {calculateAppliances} from './calculators/appliances.mjs';
import {calculateVentilation} from './calculators/ventilation.mjs';
import {calculateElectricityBill} from './calculators/electricity-bill.mjs';
const nf=new Intl.NumberFormat('es-ES',{maximumFractionDigits:2});
const n3=new Intl.NumberFormat('es-ES',{maximumFractionDigits:3});
const money=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;};
const line=(label,value)=>{const p=el('p');p.append(el('strong',label+': '),document.createTextNode(value));return p;};
function clearErrors(root){root.querySelectorAll('.error').forEach(x=>x.textContent='');root.querySelectorAll('[aria-invalid=true]').forEach(x=>x.setAttribute('aria-invalid','false'));}
function showError(root,error){
 const message=error instanceof Error?error.message:'Revisa los datos introducidos.';
 const parts=message.includes(':')?message.split(/:(.*)/s):['',message],field=parts[0],text=parts[1]||message;
 const input=field?root.querySelector('[name="'+CSS.escape(field)+'"],#'+CSS.escape(field)):null;
 const target=input&&root.querySelector('#'+CSS.escape(field)+'-error');
 if(target){target.textContent=text.trim();input.setAttribute('aria-invalid','true');input.focus();}else{const common=root.querySelector('[data-form-error]');if(common)common.textContent=message;}
 const output=root.querySelector('#result-output');output.replaceChildren(el('p','No se puede calcular todavía. Revisa los campos señalados.'));
}
function renderEnergy(output,r){const s=r.sensitivity;output.replaceChildren(el('p',money.format(r.monthlyCost),'amount'),line('Consumo mensual',nf.format(r.monthlyKwh)+' kWh'),line('Por hora',nf.format(r.hourlyKwh)+' kWh · '+money.format(r.hourlyCost)),line('Por día',nf.format(r.dailyKwh)+' kWh · '+money.format(r.dailyCost)),line('Consumo anual',nf.format(r.annualKwh)+' kWh'),line('Coste anual',money.format(r.annualCost)),el('h3','Sensibilidad de horas de uso'),line('20 % menos · '+nf.format(s.lowHours)+' h/día',nf.format(s.lowMonthlyKwh)+' kWh/mes · '+money.format(s.lowMonthlyCost)),line('Escenario introducido · '+nf.format(s.centralHours)+' h/día',nf.format(s.centralMonthlyKwh)+' kWh/mes · '+money.format(s.centralMonthlyCost)),line('20 % más · '+nf.format(s.highHours)+' h/día',nf.format(s.highMonthlyKwh)+' kWh/mes · '+money.format(s.highMonthlyCost)),el('p','Comparación de hábitos; no es un intervalo estadístico. El escenario alto se limita a 24 h/día.','help'));}
function renderThermo(output,r){const nodes=[el('p',nf.format(r.energyTank)+' kWh','amount'),line('Tiempo teórico de calentar el termo completo',nf.format(r.heatTimeHours)+' h'),line('Litros mezclados demandados al día',nf.format(r.mixedDailyLitres)+' L'),line('Demanda mezclada media por persona',nf.format(r.mixedLitresPerPerson)+' L/persona·día'),line('Agua caliente equivalente necesaria',nf.format(r.hotDailyLitres)+' L/día'),line('Agua caliente equivalente por persona',nf.format(r.hotLitresPerPerson)+' L/persona·día'),line('Litros mezclados teóricos disponibles con el termo',nf.format(r.mixedAvailableLitres)+' L'),line('Volumen mínimo teórico de acumulación para estas duchas',nf.format(r.minimumTheoreticalVolumeLitres)+' L'),line('Cobertura de la demanda introducida',r.coverage===null?'Sin demanda de ducha':nf.format(r.coverage*100)+' %'),line('Energía diaria ideal de las duchas a '+nf.format(r.showerTemp)+' °C',nf.format(r.dailyEnergy)+' kWh')];if(r.tankCost===null){nodes.push(line('Coste','No calculado: no se ha introducido precio del kWh.'));}else{nodes.push(line('Coste de calentar el termo completo',money.format(r.tankCost)),line('Coste energético diario de las duchas',money.format(r.dailyCost)));}nodes.push(el('p','Modelo teórico de mezcla sin pérdidas ni estratificación; no es una recomendación universal de tamaño de termo.','notice'));output.replaceChildren(...nodes);}
function renderDew(output,r){const state=r.condensationPossible?'Sí: la superficie está en o por debajo del punto de rocío.':'No con estos datos: la superficie está por encima del punto de rocío.';output.replaceChildren(el('p',nf.format(r.dewPoint)+' °C','amount'),line('Margen térmico superficie − rocío',nf.format(r.margin)+' °C'),line('Posibilidad física de condensación',state),el('p','Este resultado no es un diagnóstico de moho ni de salud.','notice'));}
function renderCooling(output,r){output.replaceChildren(el('p',nf.format(r.lowW/1000)+'–'+nf.format(r.highW/1000)+' kW','amount'),line('Escenario central',nf.format(r.kw)+' kW térmicos'),line('Potencia central',nf.format(r.centralW)+' W'),line('Frigorías/h',nf.format(r.frigoriaH)),line('BTU/h',nf.format(r.btuH)),el('p','Rango orientativo: no sustituye un cálculo profesional de cargas térmicas.','notice'));}
function renderTransmittance(output,r){const frag=document.createDocumentFragment();frag.append(el('p',n3.format(r.u)+' W/m²K','amount'),line('R de las capas',n3.format(r.layersR)+' m²K/W'),line('R total con superficies',n3.format(r.totalR)+' m²K/W'),line('Rsi / Rse',r.surface.rsi+' / '+r.surface.rse+' m²K/W'));r.layers.forEach((l,i)=>frag.append(line('R capa '+(i+1)+' · '+(l.name||'sin nombre'),n3.format(l.r)+' m²K/W')));if(r.extraThicknessMm!==null)frag.append(line('Espesor adicional estimado',nf.format(r.extraThicknessMm)+' mm'));output.replaceChildren(frag);}
function renderPower(output,r){output.replaceChildren(el('p',nf.format(r.scenarios.habitual/1000)+' kW','amount'),line('Suma nominal',nf.format(r.nominalW/1000)+' kW'),line('Carga individual máxima',nf.format(r.maxIndividualW/1000)+' kW'),line('Escenario moderado · max(carga máxima, 45 % de suma)',nf.format(r.scenarios.moderate/1000)+' kW'),line('Escenario habitual · max(carga máxima, 65 % de suma)',nf.format(r.scenarios.habitual/1000)+' kW'),line('Escenario intensivo · max(carga máxima, 85 % de suma)',nf.format(r.scenarios.intensive/1000)+' kW'),line('Margen hasta suma nominal',nf.format(r.marginToNominalW/1000)+' kW'),el('p','Los porcentajes son hipótesis del simulador, no factores reglamentarios ni una recomendación contractual.','notice'));}
function renderVentilation(output,r){output.replaceChildren(el('p',nf.format(r.balancedLs)+' l/s','amount'),line('Caudal equilibrado',nf.format(r.balancedM3h)+' m³/h'),line('Admisión mínima de locales secos',nf.format(r.dryMinimumLs)+' l/s'),line('Dormitorio principal',nf.format(r.mainBedroomLs)+' l/s'),line('Resto de dormitorios',nf.format(r.otherBedroomsLs)+' l/s'),line('Salas de estar/comedor',nf.format(r.livingLs)+' l/s'),line('Extracción mínima de locales húmedos',nf.format(r.wetMinimumLs)+' l/s'),line('Mínimo húmedo por número de locales',nf.format(r.wetByRoomsLs)+' l/s'),line('Aumento para equilibrar admisión',nf.format(r.admissionIncreaseLs)+' l/s'),line('Aumento para equilibrar extracción',nf.format(r.extractionIncreaseLs)+' l/s'),line('Extracción específica de cocción (independiente)',nf.format(r.kitchenSpecificExtractionLs)+' l/s'),el('p','CTE DB-HS 3 · tabla 2.1, método de caudal constante. La extracción de cocción no se suma al caudal general mostrado.','notice'));}
function renderBill(output,r){output.replaceChildren(el('p',money.format(r.total),'amount'),line('Término de energía',money.format(r.energyTerm)),line('Término de potencia',money.format(r.powerTerm)),line('Base del impuesto eléctrico en este modelo',money.format(r.electricityTaxBase)),line('Impuesto eléctrico',money.format(r.electricityTax)),line('Alquiler/equipo',money.format(r.meterRental)),line('Otros antes de IVA',money.format(r.otherBeforeVat)),line('Subtotal antes de IVA',money.format(r.beforeVat)),line('IVA',money.format(r.vat)),line('Otros después de IVA',money.format(r.otherAfterVat)),el('p','Los precios comerciales y tipos son editables. Comprueba que los campos reproducen la estructura de tu factura concreta.','notice'));}
function renderAppliances(output,r){const frag=document.createDocumentFragment();frag.append(el('p',nf.format(r.monthlyKwh)+' kWh/mes','amount'),line('Coste mensual',money.format(r.monthlyCost)),line('Consumo anual',nf.format(r.annualKwh)+' kWh'),line('Coste anual',money.format(r.annualCost)),el('h3','Ranking por consumo anual'));const ol=el('ol');r.items.forEach(i=>{ol.append(el('li',i.name+': '+nf.format(i.annualKwh)+' kWh/año · '+nf.format(i.percentage)+' % · '+money.format(i.annualCost)));});frag.append(ol);output.replaceChildren(frag);}
function genericRaw(form){return Object.fromEntries(new FormData(form));}
function collectLayers(root){return [...root.querySelectorAll('[data-layers] .dynamic-row')].map(row=>({name:row.querySelector('[name=layerName]').value,thicknessMm:row.querySelector('[name=thicknessMm]').value,lambda:row.querySelector('[name=lambda]').value}));}
function collectPower(root){return [...root.querySelectorAll('.appliance-row')].map(row=>({name:row.querySelector('[data-appliance-name]').textContent,selected:row.querySelector('[name=selected]').checked,watts:row.querySelector('[name=watts]').value}));}
function collectAppliances(root){return [...root.querySelectorAll('[data-appliances] .dynamic-row')].map(row=>({name:row.querySelector('[name=name]').value,mode:row.querySelector('[name=mode]').value,watts:row.querySelector('[name=watts]').value,hoursDay:row.querySelector('[name=hoursDay]').value,kwhCycle:row.querySelector('[name=kwhCycle]').value,cyclesWeek:row.querySelector('[name=cyclesWeek]').value}));}
function calculate(root){const form=root.querySelector('form'),kind=root.dataset.kind,output=root.querySelector('#result-output');clearErrors(root);try{if(kind==='energy')renderEnergy(output,calculateEnergy(genericRaw(form)));else if(kind==='thermo')renderThermo(output,calculateThermo(genericRaw(form)));else if(kind==='dew')renderDew(output,calculateDewPoint(genericRaw(form)));else if(kind==='cooling')renderCooling(output,calculateCooling(genericRaw(form)));else if(kind==='transmittance')renderTransmittance(output,calculateTransmittance({...genericRaw(form),layers:collectLayers(root)}));else if(kind==='power')renderPower(output,calculatePower({items:collectPower(root)}));else if(kind==='appliances')renderAppliances(output,calculateAppliances({price:form.elements.price.value,items:collectAppliances(root)}));else if(kind==='ventilation')renderVentilation(output,calculateVentilation(genericRaw(form)));else if(kind==='bill')renderBill(output,calculateElectricityBill(genericRaw(form)));}catch(error){showError(root,error);}}
function makeLayer(index){const row=el('div',undefined,'dynamic-row');const name=el('input');name.name='layerName';name.value='Capa '+index;name.setAttribute('aria-label','Nombre de la capa');const thickness=el('label');thickness.textContent='Espesor ';const tw=el('span',undefined,'input-wrap');const ti=el('input');ti.name='thicknessMm';ti.value='50';ti.inputMode='decimal';tw.append(ti,el('span','mm'));thickness.append(tw);const conductivity=el('label');conductivity.textContent='λ ';const cw=el('span',undefined,'input-wrap');const ci=el('input');ci.name='lambda';ci.value='0,040';ci.inputMode='decimal';cw.append(ci,el('span','W/(m·K)'));conductivity.append(cw);const remove=el('button','Eliminar','button tertiary');remove.type='button';remove.dataset.removeRow='';row.append(name,thickness,conductivity,remove);return row;}
function makeAppliance(index){const template=document.querySelector('[data-appliances] .dynamic-row');const row=template.cloneNode(true);row.querySelector('[name=name]').value='Aparato '+index;return row;}
function syncMode(row){const cycle=row.querySelector('[name=mode]')?.value==='cycle';row.querySelectorAll('[data-hours-field]').forEach(x=>x.hidden=cycle);row.querySelectorAll('[data-cycle-field]').forEach(x=>x.hidden=!cycle);}
document.querySelectorAll('[data-calculator]').forEach(root=>{const form=root.querySelector('form');const dynamicInitial=[...root.querySelectorAll('[data-layers],[data-appliances]')].map(node=>({node,html:node.innerHTML}));form.addEventListener('submit',e=>{e.preventDefault();calculate(root);});form.addEventListener('reset',()=>queueMicrotask(()=>{for(const item of dynamicInitial)item.node.innerHTML=item.html;root.querySelectorAll('[name=mode]').forEach(x=>syncMode(x.closest('.dynamic-row')));clearErrors(root);const output=root.querySelector('#result-output');if(output)output.replaceChildren(el('p','Valores restablecidos. Pulsa «Calcular» para actualizar.'));}));root.addEventListener('click',e=>{const target=e.target.closest('button');if(!target)return;if(target.matches('[data-add-layer]'))root.querySelector('[data-layers]').append(makeLayer(root.querySelectorAll('[data-layers] .dynamic-row').length+1));if(target.matches('[data-add-appliance]')){const row=makeAppliance(root.querySelectorAll('[data-appliances] .dynamic-row').length+1);root.querySelector('[data-appliances]').append(row);syncMode(row);}if(target.matches('[data-remove-row]')){const list=target.closest('[data-layers],[data-appliances]');if(list&&list.querySelectorAll('.dynamic-row').length>1)target.closest('.dynamic-row').remove();}});root.addEventListener('change',e=>{if(e.target.matches('[name=mode]'))syncMode(e.target.closest('.dynamic-row'));});root.querySelectorAll('[name=mode]').forEach(x=>syncMode(x.closest('.dynamic-row')));});