export const categories=[
 {slug:'energia',name:'Energía',indexable:true,description:'Calcula consumos, factura, ventilación y demanda eléctrica con tus propios datos.',future:['Comparador de calefacción']},
 {slug:'climatizacion',name:'Climatización',indexable:true,description:'Dimensiona climatización y suelo radiante con modelos transparentes y editables.',future:['Potencia de radiadores','Comparador de sistemas de climatización']},
 {slug:'aislamiento',name:'Aislamiento',indexable:true,description:'Comprueba condensación y parámetros térmicos básicos de cerramientos.',future:['Ahorro por aislamiento','Puentes térmicos simplificados']},
 {slug:'solar',name:'Solar',indexable:true,description:'Estima producción fotovoltaica utilizando resultados oficiales de PVGIS/JRC sin inventar irradiación local.',future:['Número de placas solares','Amortización solar']},
 {slug:'reformas',name:'Reformas',indexable:false,description:'Hub preparado para estimadores por partidas, con rangos y fuentes.',future:['Reforma integral','Reforma de baño','Reforma de cocina']}
];
const commonFaq=[
 ['¿Se guardan los datos que introduzco?','No. En esta V1 los cálculos se ejecutan en el navegador y los valores del formulario no se envían ni se almacenan por el código de la calculadora.'],
 ['¿El resultado sustituye a un profesional?','No. Es una herramienta orientativa basada en las variables e hipótesis visibles. Cuando una decisión requiera proyecto, verificación reglamentaria o dimensionado profesional, debe hacerse esa comprobación aparte.']
];
export const tools=[
 {
  kind:'energy',path:'climatizacion/consumo-aire-acondicionado',keywords:['consumo aire acondicionado','coste aire','kWh aire','inverter'],category:'Climatización',categorySlug:'climatizacion',short:'Consumo del aire acondicionado',icon:'❄',
  title:'Calculadora de consumo del aire acondicionado',description:'Estima kWh y coste por hora, día, mes y temporada usando la potencia eléctrica real del equipo, su utilización y tu precio del kWh.',
  methodology:'1.2',formula:'kWh = (W ÷ 1.000) × tiempo × (utilización ÷ 100) × nº de equipos. Coste = kWh × €/kWh. La sensibilidad compara −20 %, escenario introducido y +20 % de horas (máximo 24 h/día).',
  limitations:'No convierte potencia térmica en consumo eléctrico ni predice la modulación real de un equipo inverter. Si conoces una potencia media medida, introdúcela y usa utilización del 100 %.',
  example:'1.000 W, 8 h/día, 30 días, 60 % de utilización y 0,20 €/kWh → 144 kWh/mes y 28,80 €/mes.',
  fields:[['watts','Potencia eléctrica','W','1000'],['hours','Horas al día','h/día','8'],['days','Días al mes','días','30'],['factor','Utilización media','%','60'],['units','Equipos iguales','ud.','1'],['months','Meses al año','meses','3'],['price','Precio de energía','€/kWh','0,20']],
  sources:[['Virginia Tech · Estimating Appliance and Home Electronic Energy Use','https://www.pubs.ext.vt.edu/2901/2901-9014/2901-9014.html']],
  related:['energia/potencia-electrica','energia/consumo-electrodomesticos','climatizacion/calculadora-frigorias'],
  faqs:[['¿Qué potencia debo introducir?','La potencia eléctrica absorbida en W, no la potencia frigorífica o térmica.'],['¿Qué significa utilización media?','Resume qué fracción de la potencia indicada se usa de media durante las horas introducidas. Es una hipótesis editable, no una característica universal del aparato.'],['¿Incluye toda mi factura?','No. Calcula el término variable que resulta de multiplicar kWh por el precio que indiques.'],['¿Cómo calcula el año?','Multiplica el patrón mensual definido por los meses de uso. No es una predicción meteorológica.'],['¿Por qué puede diferir del consumo real?','Por modulación inverter, temperatura exterior, consigna, aislamiento y hábitos.'],...commonFaq]
 },
 {
  kind:'energy',path:'energia/consumo-radiador-electrico',keywords:['consumo radiador','calefactor eléctrico','coste calefacción','kWh radiador'],category:'Energía',categorySlug:'energia',short:'Consumo de radiador eléctrico',icon:'♨',
  title:'Calculadora de consumo de radiador eléctrico',description:'Calcula el gasto de un radiador o calefactor de resistencia a partir de su potencia, horario, termostato y precio de electricidad.',
  methodology:'1.2',formula:'kWh = (W ÷ 1.000) × horas × días × (termostato ÷ 100) × unidades. Coste = kWh × €/kWh. La sensibilidad compara −20 %, escenario introducido y +20 % de horas (máximo 24 h/día).',
  limitations:'Sirve para equipos de resistencia eléctrica. No calcula radiadores de agua ni el rendimiento de bombas de calor y no dimensiona la potencia térmica necesaria de una estancia.',
  example:'1.500 W, 5 h/día, 30 días, 70 % de utilización y 0,20 €/kWh → 157,5 kWh/mes y 31,50 €/mes.',
  fields:[['watts','Potencia eléctrica','W','1500'],['hours','Horas al día','h/día','5'],['days','Días al mes','días','30'],['factor','Termostato activo','%','70'],['units','Radiadores iguales','ud.','1'],['months','Meses al año','meses','4'],['price','Precio de energía','€/kWh','0,20']],
  sources:[['Virginia Tech · Estimating Appliance and Home Electronic Energy Use','https://www.pubs.ext.vt.edu/2901/2901-9014/2901-9014.html']],
  related:['energia/potencia-electrica','energia/consumo-electrodomesticos','aislamiento/transmitancia-termica'],
  faqs:[['¿Qué potencia uso?','La potencia eléctrica nominal del radiador indicada por el fabricante.'],['¿Qué representa el porcentaje del termostato?','La fracción del tiempo de uso durante la que la resistencia entrega potencia.'],['¿Un radiador de 1.500 W consume siempre 1,5 kWh cada hora?','Solo si permanece una hora completa entregando su potencia nominal. Con termostato puede ser menos.'],['¿Incluye costes fijos?','No. Solo el coste variable según los kWh calculados y el precio introducido.'],['¿Sirve para una bomba de calor?','No: una bomba de calor requiere relacionar energía eléctrica y calor entregado mediante su rendimiento.'],...commonFaq]
 },
 {
  kind:'thermo',path:'energia/termo-electrico',keywords:['termo eléctrico','tiempo calentamiento','agua caliente','ACS'],category:'Energía',categorySlug:'energia',short:'Termo eléctrico',icon:'♨',
  title:'Calculadora de termo eléctrico: energía y tiempo de calentamiento',description:'Calcula la energía necesaria para calentar agua, el tiempo teórico de una resistencia y compara el volumen del termo con tus litros de ducha introducidos.',
  methodology:'1.1',formula:'Mezcla: Vcaliente = Vmezcla × (Tducha − Tfría) ÷ (Ttermo − Tfría). Volumen mezclado disponible = Vtermo × (Ttermo − Tfría) ÷ (Tducha − Tfría). Energía = V × (4,186/3600) × ΔT, usando 1 L ≈ 1 kg.',
  limitations:'Modelo teórico sin pérdidas, estratificación, histéresis ni rendimiento real. La cobertura usa exactamente las duchas, litros y temperaturas introducidos; no presupone un consumo universal por persona ni recomienda un tamaño comercial.',
  example:'Con agua fría a 15 °C, uso a 40 °C y termo a 60 °C, 150 L mezclados/día requieren ≈ 83,3 L equivalentes de agua caliente del termo. La energía ideal asociada al agua mezclada es ≈ 4,36 kWh/día.',
  fields:[['persons','Personas','personas','3'],['showers','Duchas diarias','duchas','3'],['litresPerShower','Litros mezclados por ducha','L','50'],['cold','Temperatura del agua fría','°C','15'],['showerTemp','Temperatura de uso/ducha (ejemplo editable)','°C','40'],['target','Temperatura del termo','°C','60'],['powerW','Potencia resistencia','W','2000'],['volume','Volumen del termo','L','100'],['price','Precio de energía (opcional)','€/kWh','']],
  methodologyDetails:[
   'Calor específico del agua: 4,186 kJ/(kg·K), valor técnico de referencia de NIST. Dividiendo por 3.600 se obtiene ≈ 0,001163 kWh/(kg·K).',
   'Aproximación doméstica explícita: 1 litro de agua ≈ 1 kg. No se corrige la variación de densidad con la temperatura.',
   'La demanda por persona se obtiene dividiendo únicamente los litros introducidos entre el número de personas; no se aplica ningún consumo universal por persona.',
   'El balance de mezcla exige T fría < T uso/ducha < T termo.'
  ],
  sources:[['NIST · Fire Fighting Properties (NISTIR 6191): calor específico típico del agua ≈ 4,186 kJ/(kg·K)','https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir6191.pdf'],['Metodología y derivación energética del proyecto','/metodologia/']],
  related:['energia/potencia-electrica','energia/consumo-electrodomesticos','energia/consumo-radiador-electrico'],
  faqs:[['¿La calculadora recomienda un tamaño universal por persona?','No. Calcula la demanda que tú introduces y, si hay varias personas, muestra su reparto medio; no presupone litros diarios universales.'],['¿Qué significa 0,001163?','Se deriva de 4,186 kJ/(kg·K) ÷ 3.600 kJ/kWh ≈ 0,001163 kWh/(kg·K), aproximando 1 L de agua a 1 kg.'],['¿El tiempo calculado es exacto?','No. Es un tiempo teórico E/P y no incluye pérdidas, estratificación, histéresis ni control real del termo.'],['¿Puedo dejar vacío el precio del kWh?','Sí. El cálculo energético funciona y simplemente se omiten los resultados económicos.'],['¿Cómo se tiene en cuenta el agua mezclada?','Se calcula qué fracción del agua de ducha debe proceder del termo mediante balance térmico entre agua fría, temperatura de uso y temperatura del termo.'],...commonFaq]
 },
 {
  kind:'dew',path:'aislamiento/punto-de-rocio-moho',keywords:['punto de rocío','condensación','humedad','moho'],category:'Aislamiento',categorySlug:'aislamiento',short:'Punto de rocío y condensación',icon:'◌',
  title:'Calculadora de punto de rocío y condensación superficial',description:'Calcula el punto de rocío con Magnus y compara la temperatura superficial para saber si existe posibilidad física de condensación.',
  methodology:'1.0',formula:'γ = ln(HR/100) + (17,62 × T)/(243,12 + T); Td = (243,12 × γ)/(17,62 − γ).',
  limitations:'Indica posibilidad física de condensación cuando la superficie está en o por debajo del punto de rocío. No diagnostica moho, salud ni la causa constructiva de una humedad.',
  example:'Con 20 °C y 60 % HR, el punto de rocío es aproximadamente 12 °C. Una superficie a 11 °C está por debajo de ese valor y puede condensar.',
  fields:[['temperature','Temperatura interior','°C','20'],['humidity','Humedad relativa','%','60'],['surface','Temperatura superficial','°C','11'],['exterior','Temperatura exterior (opcional)','°C','']],
  sources:[['Magnus-Tetens/Sonntag: coeficientes 17,62 y 243,12 °C, rango −45 a 60 °C','https://digitalarchive.library.bogazici.edu.tr/bitstreams/d677e348-5d14-4b64-979d-de3815e49dfb/download'],['CTE · DA DB-HE/2 Condensaciones','https://www.codigotecnico.org/DocumentosCTE/AhorroEnergia.html']],
  related:['aislamiento/transmitancia-termica','energia/consumo-radiador-electrico'],
  faqs:[['¿Qué es el punto de rocío?','La temperatura a la que el aire, manteniendo su contenido de vapor, alcanza saturación y puede empezar a condensar sobre una superficie suficientemente fría.'],['¿Qué coeficientes utiliza?','17,62 y 243,12 °C para la aproximación de Magnus sobre agua.'],['¿Cuál es el rango documentado?','La referencia utilizada documenta aproximadamente −45 °C a 60 °C para la temperatura del aire.'],['¿Si la pared está por debajo del punto de rocío habrá agua visible?','Existe posibilidad física de condensación, pero el resultado no modela duración, transferencia de humedad ni acabados.'],['¿Calcula riesgo médico por moho?','No. No realiza diagnósticos médicos ni microbiológicos.'],...commonFaq]
 },
 {
  kind:'transmittance',path:'aislamiento/transmitancia-termica',keywords:['transmitancia térmica','valor U','resistencia R','espesor aislamiento'],category:'Aislamiento',categorySlug:'aislamiento',short:'Transmitancia térmica R/U',icon:'▥',
  title:'Calculadora de transmitancia térmica U, resistencia R y espesor',description:'Añade capas de un cerramiento y calcula R por capa, R total y U. También estima el espesor adicional necesario para alcanzar una U objetivo.',
  methodology:'1.0',formula:'Ri = d/λ; Rtotal = Rsi + ΣRi + Rse; U = 1/Rtotal. Para una U objetivo se despeja la resistencia adicional y su espesor.',
  limitations:'Es un cálculo unidimensional simplificado. No sustituye la verificación completa del CTE: no modela puentes térmicos, heterogeneidades, cámaras de aire complejas ni todas las condiciones de contorno.',
  example:'Capa de 100 mm con λ=0,040 W/(m·K): R=2,5 m²K/W. En un cerramiento vertical, se añaden Rsi=0,13 y Rse=0,04 m²K/W.',
  sources:[['CTE · DA DB-HE/1 Cálculo de parámetros característicos de la envolvente','https://www.codigotecnico.org/DocumentosCTE/AhorroEnergia.html']],
  related:['aislamiento/punto-de-rocio-moho','climatizacion/calculadora-frigorias'],
  faqs:[['¿Qué es R?','La resistencia térmica de una capa; en una capa homogénea se obtiene dividiendo el espesor en metros entre la conductividad λ.'],['¿Qué es U?','La transmitancia térmica del conjunto, inversa de la resistencia térmica total en este modelo.'],['¿De dónde salen Rsi y Rse?','De los valores superficiales recogidos por el documento de apoyo del CTE para la dirección del flujo considerada.'],['¿Puedo añadir varias capas?','Sí. La herramienta suma sus resistencias térmicas.'],['¿El espesor objetivo garantiza cumplimiento CTE?','No. Solo despeja un espesor dentro del modelo simplificado; la comprobación reglamentaria completa puede exigir más condiciones.'],...commonFaq]
 },
 {
  kind:'cooling',path:'climatizacion/calculadora-frigorias',keywords:['frigorías','potencia aire acondicionado','BTU','kW térmicos'],category:'Climatización',categorySlug:'climatizacion',short:'Calculadora de frigorías',icon:'❄',
  title:'Calculadora de frigorías y potencia de aire acondicionado',description:'Estima un rango de potencia de refrigeración según superficie, altura, clima, orientación, aislamiento, acristalamiento, personas y cargas internas.',
  methodology:'1.1',formula:'Base = área × referencia base × 1,163 W/(frigoría/h) × factor de altura × orientación × aislamiento × acristalamiento; después se suman personas y cargas internas. El rango se construye alrededor del resultado central.',
  limitations:'No es un cálculo profesional de cargas térmicas. Daikin respalda el rango general 100–150 frigorías/h·m² y ajustes por orientación/aislamiento; el resto de interpolaciones y factores numéricos propios se declaran expresamente como hipótesis del simulador.',
  example:'El simulador parte de 100/125/150 frigorías/h·m², corrige altura, orientación, aislamiento y acristalamiento, suma 115 W por ocupante de actividad muy ligera y las cargas internas introducidas.',
  methodologyDetails:[
   'Base climática: 100, 125 y 150 frigorías/h·m². Daikin publica 100–150 como rango general en vivienda bien aislada y clima cálido; 125 es una interpolación central propia.',
   'Altura: factor = altura/2,5 m. La corrección lineal y la referencia 2,5 m son una hipótesis simplificada del simulador.',
   'Orientación: N 0,95; E 1,00; S 1,175; O 1,10. Daikin publica +15–20 % para sur/sureste y reducción ligera al norte; los valores discretos usados aquí son interpolaciones/hipótesis propias.',
   'Aislamiento: bueno 0,90; medio 1,00; deficiente 1,15. Daikin cita aproximadamente +15 % en vivienda antigua/ventana simple; la reducción del 10 % para buen aislamiento es hipótesis propia.',
   'Acristalamiento: factor = 1 + max(0, vidrio/suelo − 0,15) × 0,5. Es una hipótesis propia y no compara físicamente m² de ventana con un máximo de m² de suelo.',
   'Ocupación: 115 W/persona como carga total representativa de ASHRAE para actividad sentada muy ligera en oficinas/hoteles/apartamentos; la carga real depende de actividad y condiciones.',
   'Rango: ±(12 % + min(8 %, relación vidrio/suelo × 20 %)), por tanto entre ±12 % y ±20 %. Es una banda heurística propia, no un intervalo estadístico.'
  ],
  sources:[['Daikin · Cómo elegir aire acondicionado split por habitación','https://www.daikin.es/es_es/hogar/inspiracion/articulos/aire-acondicionado-split-por-habitacion.html'],['Daikin · Qué son las frigorías','https://www.daikin.es/es_es/hogar/inspiracion/articulos/que-son-las-frigorias.html'],['ASHRAE Handbook · Internal Heat Gains, People: representative heat gains by activity','https://handbook.ashrae.org/handbooks/F17/SI/f17_ch18/f17_ch18_si.aspx']],
  related:['climatizacion/consumo-aire-acondicionado','energia/potencia-electrica','energia/consumo-electrodomesticos'],
  faqs:[['¿Usa 100 frigorías/m² sin más?','No. Esa referencia es solo el punto de partida; se corrige por altura, clima, orientación, aislamiento, acristalamiento, ocupación y cargas internas.'],['¿Por qué muestra un rango?','Porque una estimación doméstica simplificada no conoce todos los parámetros necesarios para una carga térmica de proyecto.'],['¿Qué diferencia hay entre kW y frigorías/h?','La herramienta usa la conversión aproximada 1 frigoría/h = 1,163 W de potencia térmica.'],['¿Influye la orientación?','Sí. La fuente consultada indica que la exposición solar puede requerir elevar la estimación, especialmente en orientaciones soleadas.'],['¿Sirve para comprar directamente un equipo?','Sirve para acotar un rango; para situaciones críticas o complejas conviene un cálculo de cargas por un profesional.'],...commonFaq]
 },
 {
  kind:'power',path:'energia/potencia-electrica',keywords:['potencia contratar','simultaneidad','kW vivienda','potencia eléctrica'],category:'Energía',categorySlug:'energia',short:'Potencia eléctrica necesaria',icon:'⚡',
  title:'Calculadora de potencia eléctrica necesaria en una vivienda',description:'Suma la potencia nominal de los aparatos que selecciones y compara escenarios de simultaneidad moderado, habitual e intensivo.',
  methodology:'1.1',formula:'Pescenario = max(Pmáxima individual, ΣPi × f). En esta V1 f = 45 %, 65 % y 85 %; el suelo Pmáxima evita estimar menos potencia que la necesaria para hacer funcionar el mayor aparato seleccionado.',
  limitations:'Los factores 45/65/85 % son hipótesis del simulador, no coeficientes reglamentarios ni una recomendación contractual. El modelo solo garantiza que cada escenario no caiga por debajo de la carga individual máxima.',
  example:'Con un único aparato de 8 kW, los tres escenarios son como mínimo 8 kW. Con varios aparatos, se toma el mayor valor entre la carga individual máxima y la suma nominal multiplicada por el factor.',
  sources:[['Metodología e hipótesis del proyecto','/metodologia/']],
  related:['energia/consumo-electrodomesticos','climatizacion/consumo-aire-acondicionado','energia/termo-electrico'],
  faqs:[['¿Por qué no suma todo y recomienda esa cifra?','Porque muchos aparatos no funcionan a la vez. La suma nominal se muestra, pero además se calculan escenarios de simultaneidad.'],['¿Los factores 45/65/85 % son oficiales?','No. Son hipótesis transparentes de esta herramienta para comparar escenarios.'],['¿Puedo editar la potencia de cada aparato?','Sí. Debes usar la potencia de tus equipos, no un valor genérico.'],['¿Incluye un cargador de vehículo eléctrico?','Sí, como opción editable, igual que el resto de aparatos.'],['¿Qué significa margen?','La diferencia entre la suma nominal y el escenario habitual estimado; no es un margen contractual recomendado.'],...commonFaq]
 },
 {
  kind:'appliances',path:'energia/consumo-electrodomesticos',keywords:['consumo electrodomésticos','consumo vivienda','kWh ciclo','ranking consumo'],category:'Energía',categorySlug:'energia',short:'Consumo de electrodomésticos',icon:'▣',
  title:'Calculadora de consumo de electrodomésticos de la vivienda',description:'Añade aparatos por potencia y horas o por kWh/ciclo y ciclos/semana. Obtén consumo, coste, porcentaje y ranking de toda la vivienda.',
  methodology:'1.0',formula:'Modo horas: kWh/año = W/1.000 × h/día × 365. Modo ciclos: kWh/año = kWh/ciclo × ciclos/semana × 52.',
  limitations:'No aporta consumos típicos ocultos: debes introducir la etiqueta, ficha técnica o medición de cada aparato. El uso anual supone que el patrón diario o semanal se mantiene.',
  example:'Un aparato de 100 W usado 5 h/día → 182,5 kWh/año. Un aparato de 1 kWh/ciclo usado 4 veces/semana → 208 kWh/año.',
  sources:[['Virginia Tech · Estimating Appliance and Home Electronic Energy Use','https://www.pubs.ext.vt.edu/2901/2901-9014/2901-9014.html']],
  related:['energia/potencia-electrica','energia/termo-electrico','climatizacion/consumo-aire-acondicionado'],
  faqs:[['¿Qué modo elijo?','Usa potencia y horas para aparatos cuyo uso se describe bien por tiempo; usa kWh/ciclo cuando el fabricante o una medición te da energía por ciclo.'],['¿De dónde saco los W o kWh/ciclo?','De la etiqueta, ficha técnica o una medición. La herramienta no impone consumos genéricos.'],['¿Cómo calcula el porcentaje?','Divide el consumo anual de cada aparato entre el total de los aparatos introducidos.'],['¿El ranking es por coste o por energía?','Se ordena por kWh/año; con un único precio del kWh el orden de coste es el mismo.'],['¿Puedo añadir y eliminar aparatos?','Sí. Las filas se gestionan localmente en el navegador.'],...commonFaq]
 },
 {
  kind:'underfloor',path:'climatizacion/suelo-radiante-tubo-circuitos',keywords:['suelo radiante','metros tubo','circuitos suelo radiante','separación tubos'],category:'Climatización',categorySlug:'climatizacion',short:'Tubo y circuitos de suelo radiante',icon:'≋',
  title:'Calculadora de tubo y circuitos de suelo radiante',description:'Estima la longitud de tubo y el número orientativo de circuitos a partir de superficie, separación, conexiones, margen y longitud máxima adoptada.',
  methodology:'1.0',reviewedAt:'06/10/2026',reviewedAtIso:'2026-10-06',
  formula:'Longitud base ≈ superficie ÷ separación (m). Longitud total = (base + conexiones) × (1 + margen/100). Circuitos = ceil(longitud total ÷ longitud máxima adoptada).',
  limitations:'Es una estimación geométrica, no un dimensionado hidráulico. La longitud máxima por circuito depende de diámetro, pérdidas de carga, caudal, colector, bomba y criterios del fabricante; debe introducirse para el sistema concreto.',
  example:'80 m² con separación 0,15 m, 10 m de conexiones y 5 % de margen → ≈ 570,5 m de tubo. Con 100 m adoptados por circuito, resultan 6 circuitos orientativos.',
  methodologyDetails:['La separación se introduce en metros para mantener coherencia dimensional con el área en m².','La longitud adicional de conexión es un dato del proyecto; no se supone automáticamente una distancia al colector.','El máximo por circuito es un límite de diseño introducido por el usuario. La fuente Uponor muestra una fórmula área/separación + conexiones y un valor propio de sistema, que no se generaliza como normativa universal.'],
  sources:[['Uponor España · Suelo radiante: cálculo de longitud y circuitos','https://www.uponor.com/es-es/soluciones/climatizacion-invisible-por-suelo-radiante'],['Uponor · Manual técnico de climatización invisible residencial','https://www.uponor.com/getmedia/f200dc36-40eb-41d0-924a-8ad45a22d7d0/manual-tecnico-suelo-radiante.pdf?sitename=Spain']],
  related:['energia/consumo-radiador-electrico','aislamiento/transmitancia-termica','energia/potencia-electrica'],
  faqs:[['¿La longitud máxima de circuito es siempre la misma?','No. Debe comprobarse para el sistema, diámetro y diseño hidráulico concretos.'],['¿Por qué la separación se expresa en metros?','Porque la relación área/separación usa m²/m y devuelve metros de tubo.'],['¿La longitud de conexión incluye ida y retorno?','Debes introducir la longitud adicional total que quieras sumar al trazado de la superficie.'],['¿Puedo sumar varias estancias?','Sí. La herramienta suma sus superficies antes de estimar longitud y circuitos.'],['¿El número de circuitos sustituye el equilibrado hidráulico?','No. Solo redondea la longitud total según el máximo que hayas introducido.'],...commonFaq]
 },
 {
  kind:'ventilation',path:'energia/ventilacion-vivienda',keywords:['ventilación vivienda','CTE HS 3','caudal ventilación','baño cocina dormitorio'],category:'Energía',categorySlug:'energia',short:'Ventilación mínima de vivienda',icon:'↝',
  title:'Calculadora de ventilación mínima de vivienda según CTE DB-HS 3',description:'Aplica la tabla 2.1 de HS 3 para ventilación de caudal constante y muestra admisión, extracción y equilibrado de la vivienda introducida.',
  methodology:'1.0',reviewedAt:'06/10/2026',reviewedAtIso:'2026-10-06',
  formula:'Se aplican los caudales de la tabla 2.1 según número de dormitorios. Mínimo húmedos = max(mínimo total, nº de locales húmedos × mínimo por local). El equilibrado eleva el lado menor hasta igualarlo con el mayor.',
  limitations:'Ayuda de cálculo para el método de caudal constante de CTE DB-HS 3. No diseña aberturas, conductos, ventiladores, distribución de caudales ni verifica todos los requisitos del proyecto. La extracción específica de 50 l/s en zona de cocción es independiente de la ventilación general.',
  example:'Para 2 dormitorios, la tabla usa 8 l/s en dormitorio principal, 4 l/s en el restante, 8 l/s por sala de estar/comedor, mínimo húmedo total 24 l/s y 7 l/s por local húmedo.',
  fields:[['bedrooms','Dormitorios','ud.','2'],['livingRooms','Salas de estar/comedor y similares','ud.','1'],['kitchens','Cocinas','ud.','1'],['bathrooms','Cuartos de baño','ud.','1'],['toilets','Aseos adicionales','ud.','0']],
  methodologyDetails:['CTE DB-HS 3, apartado 2: esta herramienta utiliza la opción de ventilación de caudal constante de la tabla 2.1.','Tabla 2.1: 0–1 dormitorios: 8 / – / 6 l/s en secos y 12 l/s total + 6 l/s por húmedo; 2 dormitorios: 8 / 4 / 8 y 24 + 7; 3 o más: 8 / 4 / 10 y 33 + 8.','El glosario de HS 3 define el equilibrado aumentando el caudal menor de admisión/extracción hasta igualarlo al mayor.','La zona de cocción requiere además extracción específica independiente mínima de 50 l/s; se informa pero no se suma a la ventilación general.'],
  sources:[['CTE · DB-HS Salubridad, HS 3 Calidad del aire interior','https://www.codigotecnico.org/pdf/Documentos/HS/DBHS.pdf'],['CTE · portal oficial Salubridad','https://www.codigotecnico.org/DocumentosCTE/Salubridad.html']],
  related:['aislamiento/punto-de-rocio-moho','aislamiento/transmitancia-termica'],
  faqs:[['¿Qué método aplica?','La ventilación de caudal constante de la tabla 2.1 del CTE DB-HS 3 consultado el 6 de octubre de 2026.'],['¿Qué significa equilibrar caudales?','Si admisión y extracción mínimas no coinciden, HS 3 indica aumentar el menor hasta igualarlo con el mayor según la hipótesis de flujo.'],['¿La campana de cocina está incluida?','No. HS 3 exige extracción específica independiente de al menos 50 l/s en la zona de cocción.'],['¿Sirve para dimensionar conductos?','No. El resultado no dimensiona conductos ni aberturas ni sustituye una comprobación completa.'],['¿Los caudales están inventados por la web?','No. Están centralizados en una configuración versionada a partir de la tabla 2.1 oficial.'],...commonFaq]
 },
 {
  kind:'bill',path:'energia/simulador-factura-electrica',keywords:['factura eléctrica','simular factura luz','impuesto electricidad','IVA luz'],category:'Energía',categorySlug:'energia',short:'Simulador de factura eléctrica',icon:'€',
  title:'Simulador de factura eléctrica con desglose editable',description:'Simula una factura con tus kWh, precios de energía y potencia, días, impuestos, alquiler y otros conceptos, sin ocultar un precio comercial actual.',
  methodology:'1.0',reviewedAt:'06/10/2026',reviewedAtIso:'2026-10-06',
  formula:'Energía = kWh × €/kWh. Potencia = kW × €/kW·día × días. Impuesto eléctrico = max(base × tipo, mínimo doméstico por MWh). IVA = base previa a IVA × tipo. Total = base previa + IVA + otros posteriores.',
  limitations:'Es un simulador de desglose, no un replicador universal de todas las tarifas. Los precios comerciales los introduce el usuario; algunos contratos, bonos, periodos horarios, descuentos o conceptos fiscales pueden requerir adaptar los campos a la factura real.',
  example:'Con 250 kWh a 0,15 €/kWh, 4,6 kW a 0,10 €/kW·día durante 30 días y los tipos editables, la herramienta desglosa cada término antes de sumar el total.',
  fields:[['consumptionKwh','Consumo del periodo','kWh','250'],['energyPrice','Precio de energía (editable)','€/kWh','0,15'],['powerKw','Potencia contratada','kW','4,6'],['powerPriceKwDay','Precio término de potencia (editable)','€/kW·día','0,10'],['days','Días del periodo','días','30'],['electricityTaxPercent','Impuesto electricidad (editable)','%','5,11269632'],['vatPercent','IVA (editable)','%','21'],['meterRental','Alquiler/equipo del periodo','€','0,81'],['otherBeforeVat','Otros conceptos antes de IVA','€','0'],['otherAfterVat','Otros conceptos después de IVA','€','0']],
  methodologyDetails:['Los precios de energía y potencia son siempre datos del usuario; los valores iniciales son ejemplos editables, no tarifas actuales.','A 06/10/2026 se muestra como referencia el tipo general del Impuesto Especial sobre la Electricidad del 5,11269632 % y mínimo doméstico de 1 €/MWh (Ley 38/1992, art. 99).','El IVA general mostrado es 21 % (Ley 37/1992, art. 90). El RDL 25/2026 prevé posibles salvaguardas condicionadas para noviembre/diciembre; por eso los tipos son editables y no se actualizan de forma oculta.','0,81 €/mes es la referencia de alquiler para contador electrónico monofásico con telegestión de la Orden IET/1491/2013; el campo de la calculadora es el importe del periodo y puede ponerse a cero o sustituirse.','El impuesto eléctrico se aplica aquí sobre energía + potencia; otros conceptos se añaden antes o después del IVA según el campo elegido. Comprueba el desglose de tu factura concreta.'],
  sources:[['BOE · Ley 38/1992, Impuesto Especial sobre la Electricidad','https://www.boe.es/buscar/act.php?id=BOE-A-1992-28741'],['BOE · Ley 37/1992, IVA','https://www.boe.es/buscar/act.php?id=BOE-A-1992-28740'],['BOE · Orden IET/1491/2013, alquiler de contador','https://www.boe.es/buscar/act.php?id=BOE-A-2013-8561'],['BOE · Real Decreto-ley 25/2026, salvaguardas energéticas','https://www.boe.es/buscar/act.php?id=BOE-A-2026-20265']],
  related:['energia/consumo-electrodomesticos','energia/potencia-electrica','climatizacion/consumo-aire-acondicionado','energia/consumo-radiador-electrico'],
  faqs:[['¿Usa el precio actual de mi comercializadora?','No. Debes introducir el precio de energía y potencia de tu contrato o factura.'],['¿Por qué puedo editar impuestos?','Porque pueden cambiar o existir situaciones específicas; la referencia vigente comprobada se muestra de forma visible, nunca oculta en el cálculo.'],['¿El alquiler de contador siempre es 0,81 €?','No. Ese valor es una referencia regulada mensual para un tipo de contador; introduce el importe real del periodo o cero si no procede.'],['¿Reproduce exactamente PVPC?','No. Esta versión simula un desglose con valores introducidos; no descarga precios horarios ni sustituye el detalle oficial de una factura PVPC.'],['¿Qué incluye el total?','Energía, potencia, impuesto eléctrico calculado, alquiler/equipo, otros conceptos, IVA y cualquier importe posterior al IVA que introduzcas.'],...commonFaq]
 },
 {
  kind:'solar',path:'solar/produccion-placas-solares',keywords:['producción placas solares','PVGIS','producción fotovoltaica','kWh kWp'],category:'Solar',categorySlug:'solar',short:'Producción de placas solares',icon:'☀',
  title:'Calculadora de producción de placas solares con PVGIS',description:'Prepara una consulta oficial PVGIS 5.3 y procesa localmente su JSON para obtener producción anual, mensual, específica y variabilidad sin inventar irradiación por provincia.',
  methodology:'1.0',reviewedAt:'06/10/2026',reviewedAtIso:'2026-10-06',
  formula:'La producción no se calcula con irradiación local inventada: PVGIS/JRC ejecuta PVcalc con ubicación, kWp, azimut, inclinación, tecnología y pérdidas. La web procesa E_y, E_m y SD_y del JSON oficial.',
  limitations:'PVGIS no permite llamadas AJAX desde navegador por su política CORS. En esta arquitectura estática se genera el enlace oficial y el usuario importa o pega el JSON. El resultado no modela sombras locales, suciedad, disponibilidad, degradación o condiciones no representadas por PVGIS.',
  example:'Introduce coordenadas, 5 kWp, orientación e inclinación; abre la consulta oficial PVGIS y procesa el JSON para ver kWh/año, kWh/kWp·año, meses y rango anual ±1 desviación estándar cuando PVGIS la facilita.',
  methodologyDetails:['Se usa el endpoint oficial PVGIS 5.3 PVcalc del Joint Research Centre.','Azimut PVGIS: 0° sur, −90° este y +90° oeste. Las pérdidas son el porcentaje introducido en la petición.','PVGIS documenta E_m como producción mensual media, E_y como producción anual media y SD_y como variabilidad interanual anual.','La API de PVGIS rechaza AJAX/CORS desde navegador; por eso no se hace fetch desde esta web ni se usa una clave privada. El JSON se procesa localmente.'],
  sources:[['JRC · PVGIS 5.3 API non-interactive service','https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis/using-pvgis-5/api-non-interactive-service_en'],['JRC · PVGIS grid-connected PV performance tool','https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis/pvgis-tools/grid-connected-pv_en']],
  related:['energia/simulador-factura-electrica','energia/consumo-electrodomesticos','energia/potencia-electrica'],
  faqs:[['¿Por qué la web no consulta PVGIS automáticamente?','El JRC indica que su API no permite acceso AJAX desde navegador por CORS. Esta V1 respeta esa limitación.'],['¿Se envían mis coordenadas a Calcula tu casa?','No. Solo se envían al JRC cuando tú abres la consulta oficial en otra pestaña.'],['¿Qué significa kWh/kWp?','Es la producción anual dividida por la potencia pico instalada, útil para comparar rendimiento específico.'],['¿Qué es el rango mostrado?','Cuando PVGIS aporta SD_y se muestra E_y ± una desviación estándar como variabilidad interanual, no como garantía.'],['¿Incluye sombras de árboles o edificios?','No necesariamente. El resultado depende de los datos y horizonte considerados por PVGIS y no sustituye un estudio de sombras local.'],...commonFaq]
 }
];
export const toolByPath=new Map(tools.map(t=>[t.path,t]));
export const infoPages=['sobre-nosotros','metodologia','fuentes','politica-editorial','contacto','aviso-legal','privacidad','cookies'];
