import {calculateConcrete} from './calculators/concrete.mjs';
const nf=new Intl.NumberFormat('es-ES',{maximumFractionDigits:3}),money=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
const root=document.querySelector('[data-concrete]');
if(root){
 const form=root.querySelector('form'),list=root.querySelector('[data-concrete-zones]'),result=root.querySelector('[data-result]'),error=root.querySelector('[data-form-error]'),initial=list.innerHTML;
 const line=(label,value)=>{const p=document.createElement('p');const s=document.createElement('strong');s.textContent=label+': ';p.append(s,document.createTextNode(value));return p;};
 const makeZone=(i)=>{const fs=document.createElement('fieldset');fs.className='reform-row';fs.dataset.zone='';fs.innerHTML='<legend>Zona '+i+'</legend><div class="fields three"><div><label>Largo</label><div class="input-wrap"><input name="lengthM" inputmode="decimal"/><span>m</span></div></div><div><label>Ancho</label><div class="input-wrap"><input name="widthM" inputmode="decimal"/><span>m</span></div></div><div><label>Espesor / altura</label><div class="input-wrap"><input name="thickness" inputmode="decimal"/><select name="thicknessUnit" aria-label="Unidad de espesor"><option value="cm">cm</option><option value="m">m</option></select></div></div></div><button class="button tertiary mt-5" type="button" data-remove-zone>Eliminar zona</button>';return fs;};
 const collect=()=>({zones:[...list.querySelectorAll('[data-zone]')].map((z,i)=>({name:'Zona '+(i+1),lengthM:z.querySelector('[name=lengthM]').value,widthM:z.querySelector('[name=widthM]').value,thickness:z.querySelector('[name=thickness]').value,thicknessUnit:z.querySelector('[name=thicknessUnit]').value})),marginPercent:form.elements.marginPercent.value,yieldLitresPerBag:form.elements.yieldLitresPerBag.value,pricePerM3:form.elements.pricePerM3.value,pricePerBag:form.elements.pricePerBag.value});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-add-zone]'))list.append(makeZone(list.querySelectorAll('[data-zone]').length+1));if(b.matches('[data-remove-zone]')&&list.querySelectorAll('[data-zone]').length>1)b.closest('[data-zone]').remove();});
 form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';try{const r=calculateConcrete(collect());const nodes=[Object.assign(document.createElement('p'),{className:'amount',textContent:nf.format(r.purchaseM3)+' m³'}),line('Volumen teórico',nf.format(r.theoreticalM3)+' m³'),line('Volumen con margen',nf.format(r.purchaseM3)+' m³'),line('Litros teóricos',nf.format(r.theoreticalLitres)+' L'),line('Litros con margen',nf.format(r.purchaseLitres)+' L')];if(r.bags!==null)nodes.push(line('Sacos redondeados',nf.format(r.bags)));if(r.cost!==null)nodes.push(line('Coste',money.format(r.cost)));const h=document.createElement('h3');h.textContent='Desglose por zonas';nodes.push(h);r.zones.forEach(z=>nodes.push(line(z.name,nf.format(z.volumeM3)+' m³')));result.replaceChildren(...nodes);}catch(err){error.textContent=err instanceof Error?err.message:'Revisa los datos.';}});
 form.addEventListener('reset',()=>queueMicrotask(()=>{list.innerHTML=initial;error.textContent='';result.replaceChildren(Object.assign(document.createElement('p'),{textContent:'Valores restablecidos. Introduce las zonas y calcula.'}));}));
}
