import {calculateLaminate} from './calculators/laminate.mjs';
const nf=new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}),money=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
const root=document.querySelector('[data-laminate]');
if(root){
 const form=root.querySelector('form'),list=root.querySelector('[data-laminate-rooms]'),result=root.querySelector('[data-result]'),error=root.querySelector('[data-form-error]'),initial=list.innerHTML;
 const line=(label,value)=>{const p=document.createElement('p');const s=document.createElement('strong');s.textContent=label+': ';p.append(s,document.createTextNode(value));return p;};
 const makeRoom=(i)=>{const row=document.createElement('div');row.className='laminate-room';row.dataset.room='';row.innerHTML='<input name="roomName" aria-label="Nombre de estancia"/><div class="fields three"><div><label>Largo <span class="input-wrap"><input name="roomLength" inputmode="decimal"/><span>m</span></span></label></div><div><label>Ancho <span class="input-wrap"><input name="roomWidth" inputmode="decimal"/><span>m</span></span></label></div><div><label>O superficie manual <span class="input-wrap"><input name="roomArea" inputmode="decimal"/><span>m²</span></span></label></div></div><button class="button tertiary" type="button" data-remove-room>Eliminar</button>';row.querySelector('[name=roomName]').value='Estancia '+i;return row;};
 const collect=()=>({rooms:[...list.querySelectorAll('[data-room]')].map(row=>({name:row.querySelector('[name=roomName]').value,length:row.querySelector('[name=roomLength]').value,width:row.querySelector('[name=roomWidth]').value,area:row.querySelector('[name=roomArea]').value})),wastePercent:form.elements.wastePercent.value,coveragePerBoxM2:form.elements.coveragePerBoxM2.value,pricePerBox:form.elements.pricePerBox.value});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-add-room]'))list.append(makeRoom(list.querySelectorAll('[data-room]').length+1));if(b.matches('[data-remove-room]')&&list.querySelectorAll('[data-room]').length>1)b.closest('[data-room]').remove();});
 form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';try{const r=calculateLaminate(collect());const amount=document.createElement('p');amount.className='amount';amount.textContent=nf.format(r.boxes)+' cajas';const nodes=[amount,line('Superficie real',nf.format(r.surfaceM2)+' m²'),line('Superficie objetivo con margen',nf.format(r.purchaseTargetM2)+' m²'),line('m² comprados',nf.format(r.purchasedM2)+' m²'),line('Sobrante frente a superficie real',nf.format(r.leftoverM2)+' m²')];if(r.cost!==null)nodes.push(line('Coste',money.format(r.cost)),line('Coste efectivo por m² real',money.format(r.effectiveCostPerM2)+'/m²'));result.replaceChildren(...nodes);}catch(err){error.textContent=err instanceof Error?err.message:'Revisa los datos.';}});
 form.addEventListener('reset',()=>queueMicrotask(()=>{list.innerHTML=initial;error.textContent='';result.replaceChildren(Object.assign(document.createElement('p'),{textContent:'Valores restablecidos. Introduce la cobertura por caja y calcula.'}));}));
}
