import {calculateStandby} from './calculators/standby.mjs';
const nf=new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}),money=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'});
const root=document.querySelector('[data-standby]');
if(root){
 const form=root.querySelector('form'),list=root.querySelector('[data-standby-items]'),result=root.querySelector('[data-result]'),error=root.querySelector('[data-form-error]'),initial=list.innerHTML;
 const line=(label,value)=>{const p=document.createElement('p');const s=document.createElement('strong');s.textContent=label+': ';p.append(s,document.createTextNode(value));return p;};
 const makeItem=(i)=>{const row=document.createElement('div');row.className='standby-row';row.dataset.item='';row.innerHTML='<input name="itemName" aria-label="Nombre del equipo"/><div class="fields"><div><label>Potencia standby <span class="input-wrap"><input name="watts" inputmode="decimal"/><span>W</span></span></label></div><div><label>Unidades <span class="input-wrap"><input name="units" value="1" inputmode="numeric"/><span>ud.</span></span></label></div><div><label>Horas standby/día <span class="input-wrap"><input name="hoursPerDay" value="24" inputmode="decimal"/><span>h</span></span></label></div><div><label>Días/año <span class="input-wrap"><input name="daysPerYear" value="365" inputmode="numeric"/><span>días</span></span></label></div></div><button class="button tertiary" type="button" data-remove-item>Eliminar</button>';row.querySelector('[name=itemName]').value='Equipo '+i;return row;};
 const collect=()=>({price:form.elements.price.value,reductionPercent:form.elements.reductionPercent.value,items:[...list.querySelectorAll('[data-item]')].map(row=>({name:row.querySelector('[name=itemName]').value,watts:row.querySelector('[name=watts]').value,units:row.querySelector('[name=units]').value,hoursPerDay:row.querySelector('[name=hoursPerDay]').value,daysPerYear:row.querySelector('[name=daysPerYear]').value}))});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-add-item]'))list.append(makeItem(list.querySelectorAll('[data-item]').length+1));if(b.matches('[data-remove-item]')&&list.querySelectorAll('[data-item]').length>1)b.closest('[data-item]').remove();});
 form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';try{const r=calculateStandby(collect());const amount=document.createElement('p');amount.className='amount';amount.textContent=nf.format(r.totalKwh)+' kWh/año';const nodes=[amount,line('Coste anual total',money.format(r.totalCost)),line('Reducción potencial analizada',nf.format(r.reductionPercent)+' %'),line('Ahorro potencial',nf.format(r.potentialSavingKwh)+' kWh/año · '+money.format(r.potentialSavingCost)),document.createElement('h3')];nodes[nodes.length-1].textContent='Ranking por equipo';const wrap=document.createElement('div');wrap.className='table-wrap';const table=document.createElement('table');table.className='data-table';table.innerHTML='<thead><tr><th>Equipo</th><th>kWh/año</th><th>€/año</th><th>% total</th></tr></thead>';const body=document.createElement('tbody');r.items.forEach(x=>{const tr=document.createElement('tr');[x.name,nf.format(x.kwh),money.format(x.cost),nf.format(x.sharePercent)+' %'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});body.append(tr);});table.append(body);wrap.append(table);nodes.push(wrap);result.replaceChildren(...nodes);}catch(err){error.textContent=err instanceof Error?err.message:'Revisa los equipos.';}});
 form.addEventListener('reset',()=>queueMicrotask(()=>{list.innerHTML=initial;error.textContent='';result.replaceChildren(Object.assign(document.createElement('p'),{textContent:'Valores restablecidos. Añade equipos y calcula.'}));}));
}
