import {calculateThermalLoss} from './calculators/thermal-loss.mjs';
const nf=new Intl.NumberFormat('es-ES',{maximumFractionDigits:2});
const root=document.querySelector('[data-thermal-loss]');
if(root){
 const form=root.querySelector('form'),list=root.querySelector('[data-thermal-elements]'),result=root.querySelector('[data-result]'),error=root.querySelector('[data-form-error]'),initial=list.innerHTML;
 const makeRow=(i)=>{const row=document.createElement('div');row.className='dynamic-row';row.dataset.element='';row.innerHTML='<input name="elementName" aria-label="Nombre del elemento"/><label>Superficie <span class="input-wrap"><input name="areaM2" inputmode="decimal"/><span>m²</span></span></label><label>Transmitancia U <span class="input-wrap"><input name="uValue" inputmode="decimal"/><span>W/(m²·K)</span></span></label><button class="button tertiary" type="button" data-remove-element>Eliminar</button>';row.querySelector('[name=elementName]').value='Elemento '+i;return row;};
 const collect=()=>({interiorTempC:form.elements.interiorTempC.value,exteriorTempC:form.elements.exteriorTempC.value,elements:[...list.querySelectorAll('[data-element]')].map(row=>({name:row.querySelector('[name=elementName]').value,areaM2:row.querySelector('[name=areaM2]').value,uValue:row.querySelector('[name=uValue]').value}))});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-add-element]'))list.append(makeRow(list.querySelectorAll('[data-element]').length+1));if(b.matches('[data-remove-element]')&&list.querySelectorAll('[data-element]').length>1)b.closest('[data-element]').remove();});
 form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';try{const r=calculateThermalLoss(collect());const nodes=[];const amount=document.createElement('p');amount.className='amount';amount.textContent=nf.format(r.totalKw)+' kW';nodes.push(amount);for(const [label,value] of [['Pérdida total',nf.format(r.totalW)+' W'],['Diferencia de temperatura',nf.format(r.deltaT)+' K']]){const p=document.createElement('p');const s=document.createElement('strong');s.textContent=label+': ';p.append(s,document.createTextNode(value));nodes.push(p);}const h=document.createElement('h3');h.textContent='Ranking por transmisión';nodes.push(h);const wrap=document.createElement('div');wrap.className='table-wrap';const table=document.createElement('table');table.className='data-table';table.innerHTML='<thead><tr><th>Elemento</th><th>Superficie</th><th>U</th><th>W</th><th>% total</th></tr></thead>';const body=document.createElement('tbody');r.elements.forEach(x=>{const tr=document.createElement('tr');[x.name,nf.format(x.areaM2)+' m²',nf.format(x.uValue)+' W/(m²·K)',nf.format(x.watts)+' W',nf.format(x.percentage)+' %'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});body.append(tr);});table.append(body);wrap.append(table);nodes.push(wrap);const note=document.createElement('p');note.className='notice';note.textContent='Solo transmisión estacionaria U × A × ΔT. No incluye ventilación, infiltraciones, puentes térmicos, ganancias solares ni inercia.';nodes.push(note);result.replaceChildren(...nodes);}catch(err){error.textContent=err instanceof Error?err.message:'Revisa los datos.';}});
 form.addEventListener('reset',()=>queueMicrotask(()=>{list.innerHTML=initial;error.textContent='';result.replaceChildren(Object.assign(document.createElement('p'),{textContent:'Valores restablecidos. Introduce los datos y calcula.'}));}));
}
